project:
  type: website
  output-dir: docs

website:
  title: "WOMBAT 2025"
  sidebar: false

  announcement: 
    icon: megaphone-fill
    dismissable: true
    content: "Save the date! This workshop will run from September 29th - 30th."
    type: warning
    position: below-navbar
    
  navbar:
    background: light
    pinned: false
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          # - text: WOMBAT conference
          #   href: about/about.qmd
          - text: Organising committee
            href: about/organizers.qmd
          # - text: Sponsors
          #   href: about/sponsors/
      - text: Program
        menu: 
          - text: Schedule
            href: program/schedule/
          # - text: Speakers
            # href: program/speakers/
      - text: Register
        href: register.qmd
      - text: Participation
        menu: 
          # - text: Call for submissions
          #   href: participation/call.qmd
          - text: Code of conduct
            href: participation/coc.qmd
          # - text: Key dates
          #   href: participation/keydates/
      - text: Contact
        href: contact.qmd
  page-footer: 
    left: "Workshop Organised by the Monash Business Analytics Team"
    right: 
      - icon: globe
        href: https://numbat.space
      - icon: github
        href: https://github.com/numbats
      # - icon: envelope
      #   href: mailto:wombat@example.com

format:
  html:
    theme: 
      light: [cosmo, css/styles.scss]
      #dark: darkly
    page-layout: custom
    toc: false

editor: visual

