project:
  type: website
  resources:
    - "CNAME"
  preview:
    port: 7878
    browser: false # setting it for my convenience cause I prefer to refresh the same tab

website:
  title: "WOMBAT 2025"
  site-url: "https://wombat2025.numbat.space"
  sidebar: false
  favicon: img/wombat/wombat-pixelart.svg

  announcement: 
    icon: megaphone-fill
    dismissable: true
    content: "Registrations are now open!"
    type: success
    position: below-navbar
    
  navbar:
    logo: img/wombat/hex-offwhite.svg
    background: light
    pinned: false
    right:
      - text: Schedule
        href: program/schedule
      - text: Workshops
        href: program/workshops.qmd
      - text: Tutorials
        href: program/tutorials.qmd
      - text: Register
        menu:
          - text: Tutorials
            href: https://events.humanitix.com/wombat-2025-day-1-tutorials
          - text: Workshop
            href: https://events.humanitix.com/wombat-2025-day-2-workshop 
      - text: Contact
        href: contact.qmd
      - text: About
        menu:
          - text: Code of Conduct
            href: participation/coc.qmd
          - text: Organising Committee
            href: about/committee.qmd
  page-footer: 
    left: "Workshop Organised by the Monash Business Analytics Team"
    right: 
      - icon: globe
        href: https://numbat.space
      - icon: github
        href: https://github.com/numbats
      # - icon: envelope
      #   href: mailto:wombat@example.com

format:
  html:
    theme: 
      light: [cosmo, css/styles.scss]
      #dark: darkly
    page-layout: custom
    toc: false

editor: visual

