project:
  type: website
  resources:
    - "CNAME"

website:
  title: "WOMBAT 2025"
  site-url: "https://wombat2025.numbat.space"
  sidebar: false

  announcement: 
    icon: megaphone-fill
    dismissable: true
    content: "Save the date! This workshop will run from September 29th - 30th."
    type: warning
    position: below-navbar
    
  navbar:
    background: light
    pinned: false
    right:
      - text: Schedule
        href: program/schedule
      - text: Register
        href: https://events.humanitix.com/open-the-world-with-open-source-wombat-2024-day-2-workshop/
      - text: Contact
        href: contact.qmd
  page-footer: 
    left: "Workshop Organised by the Monash Business Analytics Team"
    right: 
      - icon: globe
        href: https://numbat.space
      - icon: github
        href: https://github.com/numbats
      # - icon: envelope
      #   href: mailto:wombat@example.com

format:
  html:
    theme: 
      light: [cosmo, css/styles.scss]
      #dark: darkly
    page-layout: custom
    toc: false

editor: visual

