project:
  type: website
  resources:
    - "CNAME"
  preview:
    port: 7878
    browser: false # setting it for my convenience cause I prefer to refresh the same tab

website:
  title: "WOMBAT 2025"
  site-url: "https://wombat2025.numbat.space"
  sidebar: false
  favicon: img/wombat/wombat-pixelart.svg

  announcement: 
    icon: megaphone-fill
    dismissable: true
    content: "Save the date! This workshop will run from September 29th - 30th."
    type: warning
    position: below-navbar
    
  navbar:
    logo: img/wombat/hex-offwhite.svg
    background: light
    pinned: false
    right:
      # - text: Schedule
      #   menu: 
      #   - text: Workshops 
      #     href: program/schedule/workshops.qmd
      #   - text: Conference 
      #     href: program/schedule/conference.qmd
      # - text: Register
      #   href: participation/register.qmd 
      - text: Contact
        href: contact.qmd
  page-footer: 
    left: "Workshop Organised by the Monash Business Analytics Team"
    right: 
      - icon: globe
        href: https://numbat.space
      - icon: github
        href: https://github.com/numbats
      # - icon: envelope
      #   href: mailto:wombat@example.com

format:
  html:
    theme: 
      light: [cosmo, css/styles.scss]
      #dark: darkly
    page-layout: custom
    toc: false

editor: visual

