---
title: ""
format:
  html:
    include-in-header:
      - text: |
          <script type="text/javascript" src="https://conf.nectric.com.au/wombat-2025/schedule/widget/v2.en.js"></script>
listing:
  - id: keynote
    template: program/speakers/keynote.ejs
    contents: program/speakers/keynote.yml
  # - id: schedule_workshops
  #   template: program/schedule/schedule.ejs
  #   contents: program/schedule/workshops.yml
  # - id: schedule_conference
  #   template: program/schedule/schedule.ejs
  #   contents: program/schedule/conference.yml
  - id: sponsors
    template: about/sponsors/sponsors.ejs
    contents: about/sponsors/sponsors.yml
---

<!-- Truly not proud of this banner honestly. But eh c'est la vie -->
:::::::: {.grid style="width: 100vw; transform: translateX(-20%); padding-bottom: 2rem;"}
::: {.g-col-12 .title style="grid-template-columns: 1fr"}
::: {style="display: flex; flex-direction: column; align-items:center; text-align: center"}
::: {style="font-weight: bold; font-size: 3.25rem"} 
WOMBAT 2025
:::
**The Annual Workshop Organised by the Monash Business Analytics Team.**     
**29th-30th September 2025**      
[Monash University (downtown), 750 Collins St, Melbourne <svg style="width: 1rem;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M215.7 499.2C267 435 384 279.4 384 192C384 86 298 0 192 0S0 86 0 192c0 87.4 117 243 168.3 307.2c12.3 15.3 35.1 15.3 47.4 0zM192 128a64 64 0 1 1 0 128 64 64 0 1 1 0-128z"/></svg>](https://maps.app.goo.gl/F3QwdroJwyZ1sWGE8){style="color: white; font-weight: bold"}
:::
:::
:::::::: 


The purpose of this workshop is to bring together analysts from academia, industry and government to learn and discuss new open source tools for business analytics and data science. The theme of this year’s event is **designing data driven discoveries**, which will feature tutorials and talks on statistical software, research collaboration, and impactful data analysis. You should come if you are an analytics professional, or leading a team of analysts or a developer of new open source tools.


## Keynote

::: {#keynote}
:::

### Registration

Attendance will be limited to 20 participants (in-person and online) for each of the 8 tutorials on day 1, and 100 participants (in-person only) for day 2's workshop. We will also have a rich collection of hex stickers available on both days for all to choose from to decorate your laptop!

<!-- Register for one or two tutorials here and the workshop below  -->
<!-- Registrations opening soon. -->

:::{.register-btn}
[Register for the day 1 tutorials](/participation/register.html)
:::

:::{.register-btn}
[Register for the day 2 workshop](/participation/register.html)
:::

## Schedule

Please note that all session times are in AEST.

<!-- #### [Click here for a detailed workshop schedule.](program/schedule/)  -->


:::::::: grid

::: {.g-col-12 style="margin-left: 2%;"}

### Mon 29 Sep - Tutorials

```{=html}
<pretalx-schedule event-url="https://conf.nectric.com.au/wombat-2025/" locale="en" style="--schedule-max-width: 100%;--pretalx-clr-primary: #006dae;" date-filter="2025-09-29" format="grid"></pretalx-schedule>
<noscript>
   <div class="pretalx-widget">
        <div class="pretalx-widget-info-message">
            JavaScript is disabled in your browser. To access our schedule without JavaScript,
            please <a target="_blank" href="https://conf.nectric.com.au/wombat-2025/">click here</a>.
        </div>
    </div>
</noscript>
```

### Tue 30 Sep - Invited Talks

```{=html}
<pretalx-schedule event-url="https://conf.nectric.com.au/wombat-2025/" locale="en" style="--schedule-max-width: 100%;--pretalx-clr-primary: #006dae" date-filter="2025-09-30" format="grid"></pretalx-schedule>
<noscript>
   <div class="pretalx-widget">
        <div class="pretalx-widget-info-message">
            JavaScript is disabled in your browser. To access our schedule without JavaScript,
            please <a target="_blank" href="https://conf.nectric.com.au/wombat-2025/">click here</a>.
        </div>
    </div>
</noscript>

```

:::



<div>

</div>
::::::::



::: {#sponsors .g-col-12}
:::

```{=html}
<script>
  function updatePretalxScheduleFormat() {
    const schedule = document.querySelectorAll('pretalx-schedule');
    if (!schedule) return;
    if (document.body.offsetWidth > 1492) {
      schedule.forEach(x => x.setAttribute('format', 'grid'));
    } else {
      schedule.forEach(x => x.setAttribute('format', 'list'));
    }
  }

  // Run on load
  updatePretalxScheduleFormat();

  // Retrigger on window resize
  window.addEventListener('resize', updatePretalxScheduleFormat);
</script>
```
